image:
  name: atlassian/default-image:2

test: &test
  step:
    name: Test
    script:
      - npm install -g bats
      - chmod a+x test/*.bats
      - bats test/test.bats
    services:
      - docker

push: &push
  step:
    name: Push and Tag
    image: python:3.10-slim
    script:
      - pip install semversioner==0.*
      - chmod a+x ci-scripts/release.sh
      - ./ci-scripts/release.sh debricked/debricked-scan
    services:
      - docker

mirror: &mirror
  step:
    name: Mirror to GitHub
    script:
      - rm -rf ..?* .[!.]* *
      - ls -la "$BITBUCKET_CLONE_DIR"
      - git clone "$BITBUCKET_GIT_SSH_ORIGIN" "$BITBUCKET_CLONE_DIR"
      - ls -la
      - git push --mirror git@github.com:debricked/debricked-scan.git

pipelines:
  default:
    - <<: *test
  branches:
    master:
      - <<: *test
      - <<: *mirror
      - <<: *push

definitions:
  services:
    docker:
      memory: 2048
