#!/usr/bin/env bash

USERNAME="${DEBRICKED_USERNAME}"
PASSWORD="${DEBRICKED_PASSWORD}"
REPOSITORY="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
COMMIT="${CIRCLE_SHA1}"
BRANCH="${CIRCLE_BRANCH}"
BASE_DIRECTORY=${BASE_DIRECTORY:=""}
REPOSITORY_URL=${CIRCLE_REPOSITORY_URL}
INTEGRATION_NAME=circleci

source "$(dirname "$0")/common.sh"
